In [2]:
import torch

In [5]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [6]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2012, 0.7006, 0.0685],
        [0.8754, 0.0235, 0.1121],
        [0.8929, 0.1105, 0.0917],
        [0.0814, 0.0635, 0.8166],
        [0.9105, 0.9210, 0.0853]])


In [8]:
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [10]:
x = x.new_ones(5, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [16]:
x.size()

torch.Size([5, 3])

In [18]:
y = torch.rand(5, 3)
result = torch.empty(5, 3)
torch.add (x, y, out = result)

tensor([[1.4262, 1.0661, 1.0662],
        [1.6769, 1.0176, 1.9241],
        [1.8122, 1.8169, 1.8032],
        [1.3747, 1.8122, 1.2546],
        [1.7174, 1.9286, 1.4377]])

In [19]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
z

tensor([[-1.0202, -1.1443, -0.1051,  2.2824,  0.3574, -0.1758, -0.8805,  1.7793],
        [ 1.0300, -0.0786, -0.3269,  0.2332,  0.0331,  0.1424,  0.3752,  0.3183]])

CUDA Tensors

In [20]:
print(torch.cuda.is_available())
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device = device)

False
