<a href="https://colab.research.google.com/github/yeswhos/Code-Practice/blob/master/python/pytorch_practice_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor

In [34]:
import torch

In [35]:
#require grad是否接受梯度
x = torch.ones(2, 2, requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [36]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [28]:
print(y.grad_fn)

In [37]:
z = y * y * 3
#mean, 18 / 4
out = z.mean()
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [38]:
temp = torch.ones(2, 2)
z.backward(temp)

In [40]:
#z = (x + 2) ^^ 2 * 3
#z' = 6(x + 2)
#z' = 18
print(x.grad)

tensor([[18., 18.],
        [18., 18.]])


In [13]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
#前面没有说a接受梯度，所以，grad function是没有的，require grad也是false，然后也不能接受反向传播
print(a.grad_fn)
print(a.requires_grad)

None
False


In [16]:
a.requires_grad_(True)
b = (a * a).sum()
print(b.grad_fn)

# Gradient

In [22]:
#18 / 4, 如果是均值的话
#18如果是sum的话
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
