<a href="https://colab.research.google.com/github/yeswhos/Code-Practice/blob/master/python/pytorch_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

torch.manual_seed(446)
np.random.seed(446)

和numpy的关系

In [ ]:
#tensor和np相似的数组
x_numpy = np.array([0.1, 0.2, 0.3])
x_torch = torch.tensor([0.1, 0.2, 0.3])
print('x_numpy, x_torch')
print(x_numpy, x_torch)
print()

x_numpy, x_torch
[0.1 0.2 0.3] tensor([0.1000, 0.2000, 0.3000])



In [ ]:
#np和tensor转换
tensor_a = torch.from_numpy(x_numpy)
print(tensor_a)
torch_a = x_torch.numpy()
print(torch_a)

tensor([0.1000, 0.2000, 0.3000], dtype=torch.float64)
[0.1 0.2 0.3]


In [ ]:
#基本运算，相加
y_numpy = np.array([3, 4, 5.])
y_torch = torch.tensor([3, 4, 5.])
print(x_numpy + y_numpy, "numpy")
print(x_torch + y_torch)

[3.1 4.2 5.3] numpy
tensor([3.1000, 4.2000, 5.3000])


In [ ]:
#两种归一化操作（还真不是归一化），（我也没搞明白归一化具体是怎么算的）
#算就是三个数分别平方，然后加起来，然后开根号，其实就是算距离，然后也叫范数
numpy_b = np.linalg.norm(x_numpy)
print(numpy_b)
torch_b = torch.norm(x_torch)
print(torch_b)

0.37416573867739417
tensor(0.3742)


In [ ]:
x_numpy = np.array([[1, 2], [3, 4.]])
x_torch = torch.tensor([[1, 2], [3, 4.]])
print(np.mean(x_numpy, axis = 0))
print(torch.mean(x_torch, dim = 0))

[2. 3.]
tensor([2., 3.])


# What is Pytorch

In [4]:
#空的5X3矩阵
x = torch.empty(5, 3)
print(x)

tensor([[2.8861e-35, 0.0000e+00, 5.0447e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.3788e-14, 1.8369e+28, 1.9433e-19],
        [3.3738e-12, 7.4086e+28, 6.9397e+22],
        [1.7260e+25, 2.2856e+20, 5.0948e-14]])


In [5]:
#有随机数的5X3矩阵 tensor
x = torch.rand(5, 3)
print(x)

tensor([[0.2010, 0.5419, 0.0024],
        [0.3200, 0.1604, 0.6338],
        [0.5056, 0.5847, 0.8565],
        [0.0176, 0.4135, 0.1011],
        [0.5402, 0.3133, 0.7141]])


In [6]:
#0 tensor，可以指定数据类型
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
#创建一个1X1的有内容的tensor
#float类型的,建议用
x = torch.Tensor([5.5, 3])
print(x)
#整型的
y = torch.tensor([4, 3])
print(y)

tensor([5.5000, 3.0000])
tensor([4, 3])


In [16]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

y = torch.randn_like(x, dtype=torch.float)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.1258, -0.2059,  0.2778],
        [ 0.9311,  0.5823,  0.5380],
        [-2.4568,  0.7386, -0.2399],
        [-0.5507, -0.3311,  2.8829],
        [-0.4208, -2.7663,  0.1455]])


In [10]:
print(x.size())
print(y.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [17]:
#相加操作
result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)
print(result[:, 2])

tensor([[ 2.1258,  0.7941,  1.2778],
        [ 1.9311,  1.5823,  1.5380],
        [-1.4568,  1.7386,  0.7601],
        [ 0.4493,  0.6689,  3.8829],
        [ 0.5792, -1.7663,  1.1455]])
tensor([1.2778, 1.5380, 0.7601, 3.8829, 1.1455])


In [19]:
#这样才永久改变值
x.add_(y)
print(x)

tensor([[ 2.1258,  0.7941,  1.2778],
        [ 1.9311,  1.5823,  1.5380],
        [-1.4568,  1.7386,  0.7601],
        [ 0.4493,  0.6689,  3.8829],
        [ 0.5792, -1.7663,  1.1455]], dtype=torch.float64)


In [22]:
#改变格式
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(y)
print(z)

tensor([ 0.8465,  0.6114,  0.1462,  0.3910, -2.9358, -2.0018, -0.6972,  0.6025,
        -0.0061,  0.7409, -0.3454,  0.2720,  0.4914, -0.8378,  0.4136, -0.9239])
tensor([[ 0.8465,  0.6114,  0.1462,  0.3910, -2.9358, -2.0018, -0.6972,  0.6025],
        [-0.0061,  0.7409, -0.3454,  0.2720,  0.4914, -0.8378,  0.4136, -0.9239]])


In [23]:
#CUDA Tensor
if torch.cuda.is_available():
  device = torch.device("cuda")
  y = torch.ones_like(x, device = device)
  x = x.to(Device)
  z = x + y
  print(x)
  print(x.to("cpu", torch.double))