<a href="https://colab.research.google.com/github/yeswhos/Code-Practice/blob/master/python/pytorch_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

torch.manual_seed(446)
np.random.seed(446)

和numpy的关系

In [3]:
#tensor和np相似的数组
x_numpy = np.array([0.1, 0.2, 0.3])
x_torch = torch.tensor([0.1, 0.2, 0.3])
print('x_numpy, x_torch')
print(x_numpy, x_torch)
print()

x_numpy, x_torch
[0.1 0.2 0.3] tensor([0.1000, 0.2000, 0.3000])



In [5]:
#np和tensor转换
tensor_a = torch.from_numpy(x_numpy)
print(tensor_a)
torch_a = x_torch.numpy()
print(torch_a)

tensor([0.1000, 0.2000, 0.3000], dtype=torch.float64)
[0.1 0.2 0.3]


In [11]:
#基本运算，相加
y_numpy = np.array([3, 4, 5.])
y_torch = torch.tensor([3, 4, 5.])
print(x_numpy + y_numpy, "numpy")
print(x_torch + y_torch)

[3.1 4.2 5.3] numpy
tensor([3.1000, 4.2000, 5.3000])


In [13]:
#两种归一化操作（还真不是归一化），（我也没搞明白归一化具体是怎么算的）
#算就是三个数分别平方，然后加起来，然后开根号，其实就是算距离，然后也叫范数
numpy_b = np.linalg.norm(x_numpy)
print(numpy_b)
torch_b = torch.norm(x_torch)
print(torch_b)

0.37416573867739417
tensor(0.3742)


In [15]:
x_numpy = np.array([[1, 2], [3, 4.]])
x_torch = torch.tensor([[1, 2], [3, 4.]])
print(np.mean(x_numpy, axis = 0))
print(torch.mean(x_torch, dim = 0))

[2. 3.]
tensor([2., 3.])
